Creating an array with "np.random.rand(5)" which creats a "RANK-1 ARRAY". This array is neither a row vector nor a column vector.

Resulting which creates unwanted results in vector operations below are the given example to identify Rank-1 array.

To avoid the above, one should use "np.random.rand(5,1)" - a column vector or "np.random.rand(1,5)" - a row vector.

In [21]:
import numpy as np
a = np.random.randn(5)
print(a)

[-0.72547931  0.61099215 -1.58711804 -0.59688201  2.02033739]


In [22]:
print(a.shape)

(5L,)


In [23]:
print(a.T)

[-0.72547931  0.61099215 -1.58711804 -0.59688201  2.02033739]


In [24]:
print(np.dot(a,a.T))

7.856606597597075


We can use reshape to convert Rank-1 Array into some vector

In [25]:
a = a.reshape((5,1))

In [26]:
print(a.shape)

(5L, 1L)


In [27]:
print(a)

[[-0.72547931]
 [ 0.61099215]
 [-1.58711804]
 [-0.59688201]
 [ 2.02033739]]


OR, one can assert shape of Array to check on it's shape.

Python has built-in assert statement to use assertion condition in the program. assert statement has a condition or expression which is supposed to be always true. If the condition is false assert halts the program and gives an AssertionError.

Syntax: assert (condition),"error message"

In [28]:
assert(a.shape == (5,1)), "This is not a column vector of size (5,1) please check is it a Rank-1 array? "

Let's create a column vector and see the difference:

In [6]:
b = np.random.randn(5,1)
print(b)

[[ 1.38203575]
 [ 0.2708909 ]
 [-0.75018945]
 [ 1.27876704]
 [ 1.19135219]]


In [8]:
print(b.shape)

(5L, 1L)


In [7]:
print(b.T)

[[ 1.38203575  0.2708909  -0.75018945  1.27876704  1.19135219]]


In [9]:
print(np.dot(b, b.T))

[[ 1.91002281  0.3743809  -1.03678863  1.76730177  1.64649131]
 [ 0.3743809   0.07338188 -0.20321949  0.34640635  0.32272646]
 [-1.03678863 -0.20321949  0.56278421 -0.95931754 -0.89373984]
 [ 1.76730177  0.34640635 -0.95931754  1.63524515  1.52346191]
 [ 1.64649131  0.32272646 -0.89373984  1.52346191  1.41932003]]
